<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ggkickstarter"
 *
 * Auto generated by Extension Builder 2021-05-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Typo3 Kickstarter',
    'description' => 'TYPO3 Sitepackage',
    'category' => 'templates',
    'author' => 'Masoud Moradnia',
    'author_email' => 'masoud.moradnia@graphic-group.de',
    'state' => 'alpha',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
            'fluid_styled_content' => '10.4.0-10.4.99',
            // other extensions
            // 'gridelements' => '10.1.0-10.1.99',
            // 'mask' => '7.0.2-7.0.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 1
];
