base: /
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=1'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-de
    direction: ltr
    flag: de
    websiteTitle: ''
rootPageId: 1
routeEnhancers:
  Applications:
    type: Extbase
    extension: Wwapi
    plugin: Api
    routes:
      -
        routePath: '/{application_id}'
        _controller: 'Item::list'
        _arguments:
          application_id: application_id
      -
        routePath: '/{productlevel_id}'
        _controller: 'Item::list'
        _arguments:
          productlevel_id: productlevel_id
      -
        routePath: '/{sid}'
        _controller: 'Item::list'
        _arguments:
          sid: sid
      -
        routePath: '/{group}/{system_id}'
        _controller: 'Item::list'
        _arguments:
          system_id: system_id
          group: group
      -
        routePath: '/{prid}'
        _controller: 'Item::list'
        _arguments:
          system_id: prid
    defaultController: 'Item::list'
    aspects:
      application_id:
        type: PersistedAliasMapper
        tableName: tx_wwapi_domain_model_application
        routeFieldName: title
      productlevel_id:
        type: PersistedAliasMapper
        tableName: tx_wwapi_domain_model_productgroup
        routeFieldName: title
      sid:
        type: PersistedAliasMapper
        tableName: tx_wwapi_domain_model_systemgroup
        routeFieldName: title
      system_id:
        type: PersistedAliasMapper
        tableName: tx_wwapi_domain_model_system
        routeFieldName: title
      group:
        type: PersistedAliasMapper
        tableName: tx_wwapi_domain_model_systemgroup
        routeFieldName: title
      prid:
        type: PersistedAliasMapper
        tableName: tx_wwapi_domain_model_product
        routeFieldName: title
websiteTitle: ''
